import type { ConfigEnv, UserConfig } from 'vite-plus'
import path from 'node:path'
import process from 'node:process'
import { pluginAssetpack as assetpack } from './scripts/vite/plugin/assetpack-vite-plugin'
import { fullReloadWhen } from '#/vite/plugin/full-reload-by-ext.ts'
import { defineConfig } from 'vite-plus'
import devtoolsJson from 'vite-plugin-devtools-json'
import glsl from 'vite-plugin-glsl'
import { oxlint_config } from './oxlint.config'

export default defineConfig(async (_configEnv: ConfigEnv) => {
  return {
    cacheDir: path.resolve(__dirname, '.cache/vite'),
    clearScreen: true,
    server: {
      port: 3212,
      open: false,
      sourcemapIgnoreList(_sourcePath: string, _sourcemapPath: string): boolean {
        return false
      },
    },
    resolve: {
      alias: {
        '∆': path.resolve(__dirname, './src/engine'),
        '@': path.resolve(__dirname, './src/app'),
        '#': path.resolve(__dirname, './scripts'),
      },
    },
    plugins: [
      devtoolsJson(),
      glsl(),
      fullReloadWhen(['ts', 'tsx', 'frag', 'vert']).change(),
      assetpack(),
    ],
    define: {
      APP_VERSION: JSON.stringify(process.env.npm_package_version),
    },
    lint: oxlint_config,
    fmt: {
      // src/gen is generated by the AssetPack pipeline — don't churn it
      ignorePatterns: ['src/gen/**'],
      singleQuote: true,
      semi: false,
    },
    staged: {
      '*.{ts,tsx}': 'vp check --fix',
    },
  } satisfies UserConfig
})
